name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC and libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libc6-dev
          sudo apt-get install -y libx11-dev xorg-dev libxtst-dev
          sudo apt-get install -y xsel xclip
          sudo apt-get install -y libpng++-dev
          sudo apt-get install -y xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

      - name: Build Client
        uses: crazy-max/ghaction-xgo@v3
        with:
          go_version: 1.23
          dest: bin
          pkg: cmd/client
          prefix: remotecopy-client
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: true
          ldflags: -s -w
          trimpath: true

      - name: Build Server
        uses: crazy-max/ghaction-xgo@v3
        with:
          go_version: 1.23
          dest: bin
          pkg: cmd/server
          prefix: remotecopy-serer
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: true
          ldflags: -s -w
          trimpath: true

      - name: List bin directory contents
        run: ls -R ./bin


      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./build/remotecopy-*
          file_glob: true