name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tag push, adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
        include:
          - goos: linux
            goarch: amd64
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install GCC and libraries
        run: |
          sudo apt update
          sudo apt install -y gcc libc6-dev
          sudo apt install -y libx11-dev xorg-dev libxtst-dev
          sudo apt install -y xsel xclip
          sudo apt install -y libpng++-dev
          sudo apt install -y xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev


      - name: Build server binary
        run: |
          CGO_CFLAGS="-Wno-unused-command-line-argument" CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o remotecopy-server-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/server/main.go

      - name: Build client binary
        run: |
          CGO_CFLAGS="-Wno-unused-command-line-argument" CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o remotecopy-client-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/client/main.go

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: remotecopy-binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            remotecopy-server-${{ matrix.goos }}-${{ matrix.goarch }}
            remotecopy-client-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: remotecopy-server-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: remotecopy-server-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream

      - name: Upload Client Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: remotecopy-client-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: remotecopy-client-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream