name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tag push, adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC and libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libc6-dev
          sudo apt-get install -y libx11-dev xorg-dev libxtst-dev
          sudo apt-get install -y xsel xclip
          sudo apt-get install -y libpng++-dev
          sudo apt-get install -y xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.23
          dest: build
          prefix: remotecopy
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: remotecopy-server-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: remotecopy-server-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream

      - name: Upload Client Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: remotecopy-client-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: remotecopy-client-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream